apiVersion: v1
kind: Service
metadata:
  name: samir-service
  labels:
    app: samirlabs
spec:
  type: NodePort
  selector:
    app: samirlabs
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31200
